/**
 * RTE_Components.h — Keil RTE stub for STM32F103ZE
 */
#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* CMSIS */
#define RTE_CMSIS_CORE

/* Device */
#define RTE_DEVICE_STARTUP_STM32F103XE
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
#define RTE_DEVICE_STDPERIPH_GPIO
#define RTE_DEVICE_STDPERIPH_RCC
#define RTE_DEVICE_STDPERIPH_DMA
#define RTE_DEVICE_STDPERIPH_USART
#define RTE_DEVICE_STDPERIPH_FLASH

#endif /* RTE_COMPONENTS_H */
